FROM node:20-alpine AS builder
WORKDIR /app
COPY frontend/package.json ./
RUN npm install --legacy-peer-deps && \
    npm install ajv@^8 --legacy-peer-deps
COPY frontend/ .

ARG REACT_APP_BACKEND_URL=https://api-dolorosa.misdeseos.cl
ENV REACT_APP_BACKEND_URL=$REACT_APP_BACKEND_URL
ENV GENERATE_SOURCEMAP=false
ENV NODE_OPTIONS=--max-old-space-size=1536
ENV CI=false

RUN npm run build

FROM nginx:alpine
COPY --from=builder /app/build /usr/share/nginx/html
COPY frontend/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
